import "@radix-ui/themes/styles.css";
import "@/app/theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Theme } from "@radix-ui/themes";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} min-h-screen flex flex-col`}>
        <Theme
          className="h-full flex flex-col"
          appearance="dark"
          accentColor="teal"
        >
          <NavBar />
          <main className="p-5 flex-grow flex">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
